create extension if not exists pgcrypto;

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default timezone('utc', now()),
  name text not null,
  contact text not null,
  phone text,
  telegram text,
  email text,
  comment text,
  page_path text,
  source_context text,
  session_id text,
  purchase_intent_choice text,
  interest_choice text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  device_type text,
  referrer text
);

alter table public.leads add column if not exists phone text;
alter table public.leads add column if not exists telegram text;

create table if not exists public.feedback_votes (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  session_id text not null unique,
  interest_level text not null,
  page_path text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  device_type text,
  referrer text,
  constraint feedback_votes_interest_level_check
    check (interest_level in ('Очень интересно', 'Скорее интересно', 'Нейтрально', 'Неинтересно'))
);

create table if not exists public.purchase_intent (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  session_id text not null unique,
  purchase_choice text not null,
  page_path text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  device_type text,
  referrer text,
  constraint purchase_intent_choice_check
    check (
      purchase_choice in (
        'Да, купил(а) бы',
        'Возможно, если будут отзывы / подробности',
        'Возможно, если будет ниже цена',
        'Нет'
      )
    )
);

create table if not exists public.event_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  session_id text,
  event_name text not null,
  page_path text,
  section_id text,
  label text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  device_type text,
  referrer text,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.admin_users (
  email text primary key,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_leads_created_at on public.leads (created_at desc);
create index if not exists idx_leads_session_id on public.leads (session_id);
create index if not exists idx_feedback_votes_interest_level on public.feedback_votes (interest_level);
create index if not exists idx_purchase_intent_choice on public.purchase_intent (purchase_choice);
create index if not exists idx_event_logs_event_name on public.event_logs (event_name);
create index if not exists idx_event_logs_session_id on public.event_logs (session_id);
create index if not exists idx_event_logs_created_at on public.event_logs (created_at desc);

alter table public.leads enable row level security;
alter table public.feedback_votes enable row level security;
alter table public.purchase_intent enable row level security;
alter table public.event_logs enable row level security;
alter table public.admin_users enable row level security;

revoke all on table public.leads from anon, authenticated;
revoke all on table public.feedback_votes from anon, authenticated;
revoke all on table public.purchase_intent from anon, authenticated;
revoke all on table public.event_logs from anon, authenticated;
revoke all on table public.admin_users from anon, authenticated;

create or replace function public.is_admin_user()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

create or replace function public.assert_admin_access()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin_user() then
    raise exception 'admin access required';
  end if;
end;
$$;

create or replace function public.create_lead(payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_id uuid;
  input_name text := btrim(coalesce(payload ->> 'name', ''));
  input_phone text := btrim(coalesce(payload ->> 'phone', ''));
  input_telegram text := btrim(coalesce(payload ->> 'telegram', ''));
  input_contact text := btrim(coalesce(payload ->> 'contact', ''));
begin
  if input_name = '' then
    raise exception 'name is required';
  end if;

  if input_phone = '' then
    raise exception 'phone is required';
  end if;

  if input_telegram = '' then
    raise exception 'telegram is required';
  end if;

  if input_contact = '' then
    input_contact := concat_ws(' / ', input_phone, input_telegram);
  end if;

  insert into public.leads (
    name,
    contact,
    phone,
    telegram,
    email,
    comment,
    page_path,
    source_context,
    session_id,
    utm_source,
    utm_medium,
    utm_campaign,
    device_type,
    referrer
  )
  values (
    input_name,
    input_contact,
    input_phone,
    input_telegram,
    nullif(btrim(payload ->> 'email'), ''),
    nullif(btrim(payload ->> 'comment'), ''),
    nullif(payload ->> 'page_path', ''),
    nullif(payload ->> 'source_context', ''),
    nullif(payload ->> 'session_id', ''),
    nullif(payload ->> 'utm_source', ''),
    nullif(payload ->> 'utm_medium', ''),
    nullif(payload ->> 'utm_campaign', ''),
    nullif(payload ->> 'device_type', ''),
    nullif(payload ->> 'referrer', '')
  )
  returning id into inserted_id;

  return inserted_id;
end;
$$;

create or replace function public.upsert_feedback_vote(payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_id uuid;
  input_session_id text := btrim(coalesce(payload ->> 'session_id', ''));
  input_interest_level text := btrim(coalesce(payload ->> 'interest_level', ''));
begin
  if input_session_id = '' then
    raise exception 'session_id is required';
  end if;

  if input_interest_level = '' then
    raise exception 'interest_level is required';
  end if;

  insert into public.feedback_votes (
    session_id,
    interest_level,
    page_path,
    utm_source,
    utm_medium,
    utm_campaign,
    device_type,
    referrer
  )
  values (
    input_session_id,
    input_interest_level,
    nullif(payload ->> 'page_path', ''),
    nullif(payload ->> 'utm_source', ''),
    nullif(payload ->> 'utm_medium', ''),
    nullif(payload ->> 'utm_campaign', ''),
    nullif(payload ->> 'device_type', ''),
    nullif(payload ->> 'referrer', '')
  )
  on conflict (session_id) do update
  set
    interest_level = excluded.interest_level,
    page_path = excluded.page_path,
    utm_source = excluded.utm_source,
    utm_medium = excluded.utm_medium,
    utm_campaign = excluded.utm_campaign,
    device_type = excluded.device_type,
    referrer = excluded.referrer,
    updated_at = timezone('utc', now())
  returning id into inserted_id;

  return inserted_id;
end;
$$;

create or replace function public.upsert_purchase_intent(payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_id uuid;
  input_session_id text := btrim(coalesce(payload ->> 'session_id', ''));
  input_purchase_choice text := btrim(coalesce(payload ->> 'purchase_choice', ''));
begin
  if input_session_id = '' then
    raise exception 'session_id is required';
  end if;

  if input_purchase_choice = '' then
    raise exception 'purchase_choice is required';
  end if;

  insert into public.purchase_intent (
    session_id,
    purchase_choice,
    page_path,
    utm_source,
    utm_medium,
    utm_campaign,
    device_type,
    referrer
  )
  values (
    input_session_id,
    input_purchase_choice,
    nullif(payload ->> 'page_path', ''),
    nullif(payload ->> 'utm_source', ''),
    nullif(payload ->> 'utm_medium', ''),
    nullif(payload ->> 'utm_campaign', ''),
    nullif(payload ->> 'device_type', ''),
    nullif(payload ->> 'referrer', '')
  )
  on conflict (session_id) do update
  set
    purchase_choice = excluded.purchase_choice,
    page_path = excluded.page_path,
    utm_source = excluded.utm_source,
    utm_medium = excluded.utm_medium,
    utm_campaign = excluded.utm_campaign,
    device_type = excluded.device_type,
    referrer = excluded.referrer,
    updated_at = timezone('utc', now())
  returning id into inserted_id;

  return inserted_id;
end;
$$;

create or replace function public.log_event(payload jsonb)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_id bigint;
  input_event_name text := btrim(coalesce(payload ->> 'event_name', ''));
begin
  if input_event_name = '' then
    raise exception 'event_name is required';
  end if;

  insert into public.event_logs (
    session_id,
    event_name,
    page_path,
    section_id,
    label,
    utm_source,
    utm_medium,
    utm_campaign,
    device_type,
    referrer,
    metadata
  )
  values (
    nullif(payload ->> 'session_id', ''),
    input_event_name,
    nullif(payload ->> 'page_path', ''),
    nullif(payload ->> 'section_id', ''),
    nullif(payload ->> 'label', ''),
    nullif(payload ->> 'utm_source', ''),
    nullif(payload ->> 'utm_medium', ''),
    nullif(payload ->> 'utm_campaign', ''),
    nullif(payload ->> 'device_type', ''),
    nullif(payload ->> 'referrer', ''),
    coalesce(payload -> 'metadata', '{}'::jsonb)
  )
  returning id into inserted_id;

  return inserted_id;
end;
$$;

create or replace function public.get_dashboard_snapshot()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  perform public.assert_admin_access();

  with summary as (
    select
      (select count(*) from public.leads) as total_leads,
      (select count(distinct session_id) from public.event_logs where event_name = 'page_view') as unique_visitors,
      (select count(*) from public.event_logs where event_name = 'cta_click') as cta_clicks
  ),
  cta_breakdown as (
    select jsonb_agg(
      jsonb_build_object('label', labels.label, 'count', coalesce(counts.total, 0))
      order by labels.sort_order
    ) as data
    from (
      values
        ('hero_primary', 1),
        ('hero_secondary', 2),
        ('hero_quick_product', 3),
        ('hero_quick_training', 4),
        ('header_preorder', 5)
    ) as labels(label, sort_order)
    left join lateral (
      select count(*) as total
      from public.event_logs
      where event_name = 'cta_click'
        and label = labels.label
    ) counts on true
  ),
  scroll_breakdown as (
    select jsonb_agg(
      jsonb_build_object(
        'label', concat(depths.depth, '%'),
        'depth', depths.depth,
        'count', coalesce(counts.total, 0)
      )
      order by depths.depth
    ) as data
    from (
      values (25), (50), (75), (100)
    ) as depths(depth)
    left join lateral (
      select count(*) as total
      from public.event_logs
      where event_name = 'scroll_depth'
        and coalesce((metadata ->> 'depth')::int, 0) = depths.depth
    ) counts on true
  )
  select jsonb_build_object(
    'updatedAt', timezone('utc', now()),
    'summary', jsonb_build_object(
      'totalLeads', summary.total_leads,
      'uniqueVisitors', summary.unique_visitors,
      'formConversion',
        case
          when summary.unique_visitors > 0
            then round(((summary.total_leads::numeric / summary.unique_visitors::numeric) * 100), 1)
          else 0
        end,
      'ctaClicks', summary.cta_clicks
    ),
    'ctaBreakdown', coalesce((select data from cta_breakdown), '[]'::jsonb),
    'scrollDepth', coalesce((select data from scroll_breakdown), '[]'::jsonb)
  )
  into result
  from summary;

  return result;
end;
$$;

create or replace function public.get_recent_leads(limit_count int default 50)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  perform public.assert_admin_access();

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', leads.id,
        'created_at', leads.created_at,
        'name', leads.name,
        'phone', leads.phone,
        'telegram', leads.telegram,
        'contact', leads.contact,
        'email', leads.email,
        'comment', leads.comment,
        'source_context', leads.source_context,
        'page_path', leads.page_path,
        'referrer', leads.referrer,
        'utm_source', leads.utm_source,
        'utm_medium', leads.utm_medium,
        'utm_campaign', leads.utm_campaign
      )
      order by leads.created_at desc
    ),
    '[]'::jsonb
  )
  into result
  from (
    select *
    from public.leads
    order by created_at desc
    limit greatest(limit_count, 1)
  ) as leads;

  return result;
end;
$$;

grant execute on function public.create_lead(jsonb) to anon, authenticated;
grant execute on function public.upsert_feedback_vote(jsonb) to anon, authenticated;
grant execute on function public.upsert_purchase_intent(jsonb) to anon, authenticated;
grant execute on function public.log_event(jsonb) to anon, authenticated;
grant execute on function public.is_admin_user() to anon, authenticated;
grant execute on function public.assert_admin_access() to anon, authenticated;
grant execute on function public.get_dashboard_snapshot() to anon, authenticated;
grant execute on function public.get_recent_leads(int) to anon, authenticated;

-- После выполнения схемы добавьте свой email администратора:
-- insert into public.admin_users (email) values ('you@example.com')
-- on conflict (email) do nothing;
